import Head from "next/head"
import Link from "next/link"

interface LayoutProps {
  children: React.ReactNode
  title?: string
}

export default function Layout({ children, title = "Takoyakita App" }: LayoutProps) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta charSet="UTF-8" />
        <meta name="description" content="Generated by Parcela Producer" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-screen bg-red-950 text-white relative overflow-hidden">
        {/* Fixed Header */}
        <header className="p-2 bg-red-900 w-full text-center fixed top-0 z-10">
          <h1 className="text-lg text-red-200 font-semibold">Takoyakita App</h1>
        </header>

        {/* Scrollable Main */}
        <main className="absolute top-12 bottom-12 left-0 right-0 overflow-y-auto px-4 py-2">
          {children}
        </main>

        {/* Fixed Footer */}
        <footer className="w-full flex fixed bottom-0 z-10">
          <Link
            href="/transactions"
            className="flex-1 bg-red-700 text-center py-2 text-white font-semibold"
          >
            Buat Pesanan
          </Link>
          <Link
            href="/reports"
            className="flex-1 bg-red-800 text-center py-2 text-white font-semibold"
          >
            List Pesanan
          </Link>
        </footer>
      </div>
    </>
  )
}
